### ISSUE TITLE
FEATURE REQUEST: Turn contigouus text into specific callouts

### ISSUE THREAD

**Issue by mariomui** [blorbb/obsidian-blockier#1]
As a note taker that converts paragraphs into quotes (in order to prettify the manually extracted quotes from a book),  I'd like a shortcut to convert a block into a quote callout automatically.

testing
testing <--- when i do specific command (say `⌥  + ⌘  + Q`) 

> [!quote] testing
> testing

**Comment by blorbb** [comment]
Thanks for the suggestion! I think this feature is already in Obsidian though, see the commands "Toggle blockquote" or "Insert callout", which you can assign a hotkey to.

A command just for a quote callout seems too specific of a use case; using "Insert callout" automatically places your cursor in "[!`NOTE`]", then typing `q` `enter` (autocomplete for quote) might work for you.

Or if you meant some other functionality, feel free to elaborate. I'll close this issue for now though.
