### ISSUE TITLE
Callout suggestions only appear if there is a space after '>'

### ISSUE THREAD

**Issue by luisneto** [blorbb/obsidian-blockier#5]
I have noticed that the callout suggestions only works if there is a space between `>` and `[`.
However, that space is not a requirement for a well-formed callout.

Could the plugin be modified so that suggestions appear regardless of whether the space is there?

Thank you in advance.

**Comment by blorbb** [comment]
Didn't know that was allowed! This should be relatively easy to add, I'll make the change tomorrow.

**Comment by luisneto** [comment]
Thank you, @blorbb!
